CC = gcc
CFLAGS = -std=c11 -Wall -Werror 
TARGET = zadanie3
SRC = zadanie3.c

all: $(SRC)
	$(CC) $(CFLAGS) $(SRC) -o $(TARGET)

compile:
	$(CC) $(FLAGS) $(SRC) -o $(TARGET)

clean:
	rm -f $(TARGET)